// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJMDO-ON6gM3gv-T_RaxqdbRs5lCvq2AE',
    appId: '1:28094799186:web:8db2387dfa91a0e3e86e8b',
    messagingSenderId: '28094799186',
    projectId: 'car-rent-flutter-app',
    authDomain: 'car-rent-flutter-app.firebaseapp.com',
    storageBucket: 'car-rent-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3UzFHLn-FmaOsSYk0ulX5GPxKKnXCwk',
    appId: '1:28094799186:android:ac500587088c61b1e86e8b',
    messagingSenderId: '28094799186',
    projectId: 'car-rent-flutter-app',
    storageBucket: 'car-rent-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk6OckqkuXBSgfRuORSp7rg6exaohx-VM',
    appId: '1:28094799186:ios:726acf3d2d3e4094e86e8b',
    messagingSenderId: '28094799186',
    projectId: 'car-rent-flutter-app',
    storageBucket: 'car-rent-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.rentCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk6OckqkuXBSgfRuORSp7rg6exaohx-VM',
    appId: '1:28094799186:ios:726acf3d2d3e4094e86e8b',
    messagingSenderId: '28094799186',
    projectId: 'car-rent-flutter-app',
    storageBucket: 'car-rent-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.rentCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJMDO-ON6gM3gv-T_RaxqdbRs5lCvq2AE',
    appId: '1:28094799186:web:74abaf843791ed54e86e8b',
    messagingSenderId: '28094799186',
    projectId: 'car-rent-flutter-app',
    authDomain: 'car-rent-flutter-app.firebaseapp.com',
    storageBucket: 'car-rent-flutter-app.firebasestorage.app',
  );
}
